services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '5050:5050'
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /Users/jerome/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD='guang'
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/jerome/redis:/data
